upstream patient_service {
    server patient-service:8018;
}

upstream clinical_service {
    server clinical-service:8017;
}

upstream appointment_service {
    server appointment-service:8016;
}

server {
    listen 80;
    server_name clinical.medtrustx.internal;

    location /api/patient/ {
        proxy_pass http://patient_service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/clinical/ {
        proxy_pass http://clinical_service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/appointments/ {
        proxy_pass http://appointment_service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
