upstream kong {
    server kong-gateway-service:8000;
}

upstream composition {
    server api-composition-gateway:8022;
}

upstream graphql {
    server graphql-federation-gateway:8023;
}

server {
    listen 80;
    server_name api.medtrustx.local;

    location /graphql {
        proxy_pass http://graphql;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/composed {
        proxy_pass http://composition;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://kong;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
