"""
MedTrustX Billing Service — Domain Entities

Tables:
  charges      – Individual monetizable events (consultation, lab test, medication)
  invoices     – Aggregation of charges billed to a patient
  invoice_items– Line items on a specific invoice
  payments     – Financial settlement transactions against an invoice
  adjustments  – Discounts, write-offs, or corrections
"""
import uuid
from datetime import datetime
from decimal import Decimal
from typing import List, Optional

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import BaseModel


class Charge(BaseModel):
    """
    An atomic billable event generated by upstream systems (e.g., pharmacy dispensing).
    """

    __tablename__ = "charges"
    __table_args__ = (
        Index("ix_charges_patient", "tenant_id", "patient_id"),
        Index("ix_charges_status", "tenant_id", "status"),
        {"comment": "Raw billable clinical/operational events"},
    )

    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
    )

    encounter_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
    )

    service_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="consultation | pharmacy | diagnostics | surgery | room",
    )

    reference_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        comment="ID of the source entity (e.g., appointment_id or lab_order_id)",
    )

    amount: Mapped[Decimal] = mapped_column(
        Numeric(10, 2),
        nullable=False,
    )

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="pending",
        server_default=text("'pending'"),
        comment="pending | invoiced | voided",
    )


class Invoice(BaseModel):
    """
    The formal bill presented to the patient or insurance.
    """

    __tablename__ = "invoices"
    __table_args__ = (
        Index("ix_invoices_patient", "tenant_id", "patient_id"),
        Index("ix_invoices_status_due", "tenant_id", "status", "due_date"),
        {"comment": "Aggregated patient bills"},
    )

    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
    )

    total_amount: Mapped[Decimal] = mapped_column(
        Numeric(10, 2),
        nullable=False,
        default=0.00,
    )

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="draft",
        server_default=text("'draft'"),
        comment="draft | issued | partial | paid | overdue | cancelled",
    )

    issued_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    due_date: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # ── Relationships ───────────────────────────────────────────
    items: Mapped[List["InvoiceItem"]] = relationship(
        "InvoiceItem", back_populates="invoice", cascade="all, delete-orphan"
    )
    payments: Mapped[List["Payment"]] = relationship(
        "Payment", back_populates="invoice", cascade="all, delete-orphan"
    )
    adjustments: Mapped[List["Adjustment"]] = relationship(
        "Adjustment", back_populates="invoice", cascade="all, delete-orphan"
    )


class InvoiceItem(BaseModel):
    """
    Line items explicitly associated with an invoice.
    Can be mapped 1:1 to a Charge, or arbitrarily added.
    """

    __tablename__ = "invoice_items"
    __table_args__ = (
        Index("ix_inv_items_invoice", "tenant_id", "invoice_id"),
        {"comment": "Invoice line items"},
    )

    invoice_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("invoices.id", ondelete="CASCADE"),
        nullable=False,
    )

    description: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    amount: Mapped[Decimal] = mapped_column(
        Numeric(10, 2),
        nullable=False,
    )

    # Optional link back to the raw charge that spawned this item
    charge_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("charges.id"),
        nullable=True,
    )

    # ── Relationships ───────────────────────────────────────────
    invoice: Mapped["Invoice"] = relationship("Invoice", back_populates="items")


class Payment(BaseModel):
    """
    Financial settlements against an invoice.
    """

    __tablename__ = "payments"
    __table_args__ = (
        Index("ix_payments_invoice", "tenant_id", "invoice_id"),
        {"comment": "Financial settlements"},
    )

    invoice_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("invoices.id", ondelete="CASCADE"),
        nullable=False,
    )

    amount: Mapped[Decimal] = mapped_column(
        Numeric(10, 2),
        nullable=False,
    )

    payment_method: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="cash | credit_card | insurance | bank_transfer",
    )

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="pending",
        server_default=text("'pending'"),
        comment="pending | completed | failed | refunded",
    )

    paid_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # ── Relationships ───────────────────────────────────────────
    invoice: Mapped["Invoice"] = relationship("Invoice", back_populates="payments")


class Adjustment(BaseModel):
    """
    Corrections, discounts, or write-offs applied to an invoice.
    """

    __tablename__ = "adjustments"
    __table_args__ = (
        Index("ix_adjustments_invoice", "tenant_id", "invoice_id"),
        {"comment": "Financial corrections and discounts"},
    )

    invoice_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("invoices.id", ondelete="CASCADE"),
        nullable=False,
    )

    adjustment_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="discount | tax | write_off | correction",
    )

    amount: Mapped[Decimal] = mapped_column(
        Numeric(10, 2),
        nullable=False,
        comment="Can be negative for discounts, positive for taxes/fees",
    )

    reason: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # ── Relationships ───────────────────────────────────────────
    invoice: Mapped["Invoice"] = relationship("Invoice", back_populates="adjustments")
