/**
 * AUTO-GENERATED MEDTRUSTX ENDPOINTS
 * Full integration mapping for all 139+ microservices.
 */
export const autoEndpoints = {
  accessControl: {
    list: '/api/v1/access-control',
    getById: (id: string) => `/api/v1/access-control/${id}`,
    create: '/api/v1/access-control',
    update: (id: string) => `/api/v1/access-control/${id}`,
    delete: (id: string) => `/api/v1/access-control/${id}`,
  },
  accessReview: {
    list: '/api/v1/access-review',
    getById: (id: string) => `/api/v1/access-review/${id}`,
    create: '/api/v1/access-review',
    update: (id: string) => `/api/v1/access-review/${id}`,
    delete: (id: string) => `/api/v1/access-review/${id}`,
  },
  accreditation: {
    list: '/api/v1/accreditation',
    getById: (id: string) => `/api/v1/accreditation/${id}`,
    create: '/api/v1/accreditation',
    update: (id: string) => `/api/v1/accreditation/${id}`,
    delete: (id: string) => `/api/v1/accreditation/${id}`,
  },
  ai: {
    list: '/api/v1/ai',
    getById: (id: string) => `/api/v1/ai/${id}`,
    create: '/api/v1/ai',
    update: (id: string) => `/api/v1/ai/${id}`,
    delete: (id: string) => `/api/v1/ai/${id}`,
  },
  aiGovernanceExplainability: {
    list: '/api/v1/ai-governance-explainability',
    getById: (id: string) => `/api/v1/ai-governance-explainability/${id}`,
    create: '/api/v1/ai-governance-explainability',
    update: (id: string) => `/api/v1/ai-governance-explainability/${id}`,
    delete: (id: string) => `/api/v1/ai-governance-explainability/${id}`,
  },
  aiPlatform: {
    list: '/api/v1/ai-platform',
    getById: (id: string) => `/api/v1/ai-platform/${id}`,
    create: '/api/v1/ai-platform',
    update: (id: string) => `/api/v1/ai-platform/${id}`,
    delete: (id: string) => `/api/v1/ai-platform/${id}`,
  },
  alertCorrelationEngine: {
    list: '/api/v1/alert-correlation-engine',
    getById: (id: string) => `/api/v1/alert-correlation-engine/${id}`,
    create: '/api/v1/alert-correlation-engine',
    update: (id: string) => `/api/v1/alert-correlation-engine/${id}`,
    delete: (id: string) => `/api/v1/alert-correlation-engine/${id}`,
  },
  analytics: {
    list: '/api/v1/analytics',
    getById: (id: string) => `/api/v1/analytics/${id}`,
    create: '/api/v1/analytics',
    update: (id: string) => `/api/v1/analytics/${id}`,
    delete: (id: string) => `/api/v1/analytics/${id}`,
  },
  apiCompositionGateway: {
    list: '/api/v1/api-composition-gateway',
    getById: (id: string) => `/api/v1/api-composition-gateway/${id}`,
    create: '/api/v1/api-composition-gateway',
    update: (id: string) => `/api/v1/api-composition-gateway/${id}`,
    delete: (id: string) => `/api/v1/api-composition-gateway/${id}`,
  },
  appointment: {
    list: '/api/v1/appointment',
    getById: (id: string) => `/api/v1/appointment/${id}`,
    create: '/api/v1/appointment',
    update: (id: string) => `/api/v1/appointment/${id}`,
    delete: (id: string) => `/api/v1/appointment/${id}`,
  },
  assetTrackingRtls: {
    list: '/api/v1/asset-tracking-rtls',
    getById: (id: string) => `/api/v1/asset-tracking-rtls/${id}`,
    create: '/api/v1/asset-tracking-rtls',
    update: (id: string) => `/api/v1/asset-tracking-rtls/${id}`,
    delete: (id: string) => `/api/v1/asset-tracking-rtls/${id}`,
  },
  audit: {
    list: '/api/v1/audit',
    getById: (id: string) => `/api/v1/audit/${id}`,
    create: '/api/v1/audit',
    update: (id: string) => `/api/v1/audit/${id}`,
    delete: (id: string) => `/api/v1/audit/${id}`,
  },
  automationRpaEngine: {
    list: '/api/v1/automation-rpa-engine',
    getById: (id: string) => `/api/v1/automation-rpa-engine/${id}`,
    create: '/api/v1/automation-rpa-engine',
    update: (id: string) => `/api/v1/automation-rpa-engine/${id}`,
    delete: (id: string) => `/api/v1/automation-rpa-engine/${id}`,
  },
  bedManagement: {
    list: '/api/v1/bed-management',
    getById: (id: string) => `/api/v1/bed-management/${id}`,
    create: '/api/v1/bed-management',
    update: (id: string) => `/api/v1/bed-management/${id}`,
    delete: (id: string) => `/api/v1/bed-management/${id}`,
  },
  billing: {
    list: '/api/v1/billing',
    getById: (id: string) => `/api/v1/billing/${id}`,
    create: '/api/v1/billing',
    update: (id: string) => `/api/v1/billing/${id}`,
    delete: (id: string) => `/api/v1/billing/${id}`,
  },
  biomedicalEngineering: {
    list: '/api/v1/biomedical-engineering',
    getById: (id: string) => `/api/v1/biomedical-engineering/${id}`,
    create: '/api/v1/biomedical-engineering',
    update: (id: string) => `/api/v1/biomedical-engineering/${id}`,
    delete: (id: string) => `/api/v1/biomedical-engineering/${id}`,
  },
  bloodBank: {
    list: '/api/v1/blood-bank',
    getById: (id: string) => `/api/v1/blood-bank/${id}`,
    create: '/api/v1/blood-bank',
    update: (id: string) => `/api/v1/blood-bank/${id}`,
    delete: (id: string) => `/api/v1/blood-bank/${id}`,
  },
  boardReporting: {
    list: '/api/v1/board-reporting',
    getById: (id: string) => `/api/v1/board-reporting/${id}`,
    create: '/api/v1/board-reporting',
    update: (id: string) => `/api/v1/board-reporting/${id}`,
    delete: (id: string) => `/api/v1/board-reporting/${id}`,
  },
  careCoordination: {
    list: '/api/v1/care-coordination',
    getById: (id: string) => `/api/v1/care-coordination/${id}`,
    create: '/api/v1/care-coordination',
    update: (id: string) => `/api/v1/care-coordination/${id}`,
    delete: (id: string) => `/api/v1/care-coordination/${id}`,
  },
  caseManagement: {
    list: '/api/v1/case-management',
    getById: (id: string) => `/api/v1/case-management/${id}`,
    create: '/api/v1/case-management',
    update: (id: string) => `/api/v1/case-management/${id}`,
    delete: (id: string) => `/api/v1/case-management/${id}`,
  },
  cctvSurveillance: {
    list: '/api/v1/cctv-surveillance',
    getById: (id: string) => `/api/v1/cctv-surveillance/${id}`,
    create: '/api/v1/cctv-surveillance',
    update: (id: string) => `/api/v1/cctv-surveillance/${id}`,
    delete: (id: string) => `/api/v1/cctv-surveillance/${id}`,
  },
  cdss: {
    list: '/api/v1/cdss',
    getById: (id: string) => `/api/v1/cdss/${id}`,
    create: '/api/v1/cdss',
    update: (id: string) => `/api/v1/cdss/${id}`,
    delete: (id: string) => `/api/v1/cdss/${id}`,
  },
  clickhouseAnalytics: {
    list: '/api/v1/clickhouse-analytics',
    getById: (id: string) => `/api/v1/clickhouse-analytics/${id}`,
    create: '/api/v1/clickhouse-analytics',
    update: (id: string) => `/api/v1/clickhouse-analytics/${id}`,
    delete: (id: string) => `/api/v1/clickhouse-analytics/${id}`,
  },
  clinical: {
    list: '/api/v1/clinical',
    getById: (id: string) => `/api/v1/clinical/${id}`,
    create: '/api/v1/clinical',
    update: (id: string) => `/api/v1/clinical/${id}`,
    delete: (id: string) => `/api/v1/clinical/${id}`,
  },
  clinicalPathwayIntelligence: {
    list: '/api/v1/clinical-pathway-intelligence',
    getById: (id: string) => `/api/v1/clinical-pathway-intelligence/${id}`,
    create: '/api/v1/clinical-pathway-intelligence',
    update: (id: string) => `/api/v1/clinical-pathway-intelligence/${id}`,
    delete: (id: string) => `/api/v1/clinical-pathway-intelligence/${id}`,
  },
  clinicalResearch: {
    list: '/api/v1/clinical-research',
    getById: (id: string) => `/api/v1/clinical-research/${id}`,
    create: '/api/v1/clinical-research',
    update: (id: string) => `/api/v1/clinical-research/${id}`,
    delete: (id: string) => `/api/v1/clinical-research/${id}`,
  },
  compliance: {
    list: '/api/v1/compliance',
    getById: (id: string) => `/api/v1/compliance/${id}`,
    create: '/api/v1/compliance',
    update: (id: string) => `/api/v1/compliance/${id}`,
    delete: (id: string) => `/api/v1/compliance/${id}`,
  },
  complianceEnforcement: {
    list: '/api/v1/compliance-enforcement',
    getById: (id: string) => `/api/v1/compliance-enforcement/${id}`,
    create: '/api/v1/compliance-enforcement',
    update: (id: string) => `/api/v1/compliance-enforcement/${id}`,
    delete: (id: string) => `/api/v1/compliance-enforcement/${id}`,
  },
  complianceGovernance: {
    list: '/api/v1/compliance-governance',
    getById: (id: string) => `/api/v1/compliance-governance/${id}`,
    create: '/api/v1/compliance-governance',
    update: (id: string) => `/api/v1/compliance-governance/${id}`,
    delete: (id: string) => `/api/v1/compliance-governance/${id}`,
  },
  configuration: {
    list: '/api/v1/configuration',
    getById: (id: string) => `/api/v1/configuration/${id}`,
    create: '/api/v1/configuration',
    update: (id: string) => `/api/v1/configuration/${id}`,
    delete: (id: string) => `/api/v1/configuration/${id}`,
  },
  consent: {
    list: '/api/v1/consent',
    getById: (id: string) => `/api/v1/consent/${id}`,
    create: '/api/v1/consent',
    update: (id: string) => `/api/v1/consent/${id}`,
    delete: (id: string) => `/api/v1/consent/${id}`,
  },
  coturnRelay: {
    list: '/api/v1/coturn-relay',
    getById: (id: string) => `/api/v1/coturn-relay/${id}`,
    create: '/api/v1/coturn-relay',
    update: (id: string) => `/api/v1/coturn-relay/${id}`,
    delete: (id: string) => `/api/v1/coturn-relay/${id}`,
  },
  credentialing: {
    list: '/api/v1/credentialing',
    getById: (id: string) => `/api/v1/credentialing/${id}`,
    create: '/api/v1/credentialing',
    update: (id: string) => `/api/v1/credentialing/${id}`,
    delete: (id: string) => `/api/v1/credentialing/${id}`,
  },
  dataFabricIntegrationHub: {
    list: '/api/v1/data-fabric-integration-hub',
    getById: (id: string) => `/api/v1/data-fabric-integration-hub/${id}`,
    create: '/api/v1/data-fabric-integration-hub',
    update: (id: string) => `/api/v1/data-fabric-integration-hub/${id}`,
    delete: (id: string) => `/api/v1/data-fabric-integration-hub/${id}`,
  },
  dataGovernance: {
    list: '/api/v1/data-governance',
    getById: (id: string) => `/api/v1/data-governance/${id}`,
    create: '/api/v1/data-governance',
    update: (id: string) => `/api/v1/data-governance/${id}`,
    delete: (id: string) => `/api/v1/data-governance/${id}`,
  },
  device: {
    list: '/api/v1/device',
    getById: (id: string) => `/api/v1/device/${id}`,
    create: '/api/v1/device',
    update: (id: string) => `/api/v1/device/${id}`,
    delete: (id: string) => `/api/v1/device/${id}`,
  },
  devices: {
    list: '/api/v1/devices',
    getById: (id: string) => `/api/v1/devices/${id}`,
    create: '/api/v1/devices',
    update: (id: string) => `/api/v1/devices/${id}`,
    delete: (id: string) => `/api/v1/devices/${id}`,
  },
  diagnostics: {
    list: '/api/v1/diagnostics',
    getById: (id: string) => `/api/v1/diagnostics/${id}`,
    create: '/api/v1/diagnostics',
    update: (id: string) => `/api/v1/diagnostics/${id}`,
    delete: (id: string) => `/api/v1/diagnostics/${id}`,
  },
  dietNutrition: {
    list: '/api/v1/diet-nutrition',
    getById: (id: string) => `/api/v1/diet-nutrition/${id}`,
    create: '/api/v1/diet-nutrition',
    update: (id: string) => `/api/v1/diet-nutrition/${id}`,
    delete: (id: string) => `/api/v1/diet-nutrition/${id}`,
  },
  digitalTwinEngine: {
    list: '/api/v1/digital-twin-engine',
    getById: (id: string) => `/api/v1/digital-twin-engine/${id}`,
    create: '/api/v1/digital-twin-engine',
    update: (id: string) => `/api/v1/digital-twin-engine/${id}`,
    delete: (id: string) => `/api/v1/digital-twin-engine/${id}`,
  },
  edgeConnectivityManager: {
    list: '/api/v1/edge-connectivity-manager',
    getById: (id: string) => `/api/v1/edge-connectivity-manager/${id}`,
    create: '/api/v1/edge-connectivity-manager',
    update: (id: string) => `/api/v1/edge-connectivity-manager/${id}`,
    delete: (id: string) => `/api/v1/edge-connectivity-manager/${id}`,
  },
  enterpriseRiskOversight: {
    list: '/api/v1/enterprise-risk-oversight',
    getById: (id: string) => `/api/v1/enterprise-risk-oversight/${id}`,
    create: '/api/v1/enterprise-risk-oversight',
    update: (id: string) => `/api/v1/enterprise-risk-oversight/${id}`,
    delete: (id: string) => `/api/v1/enterprise-risk-oversight/${id}`,
  },
  er: {
    list: '/api/v1/er',
    getById: (id: string) => `/api/v1/er/${id}`,
    create: '/api/v1/er',
    update: (id: string) => `/api/v1/er/${id}`,
    delete: (id: string) => `/api/v1/er/${id}`,
  },
  ethics: {
    list: '/api/v1/ethics',
    getById: (id: string) => `/api/v1/ethics/${id}`,
    create: '/api/v1/ethics',
    update: (id: string) => `/api/v1/ethics/${id}`,
    delete: (id: string) => `/api/v1/ethics/${id}`,
  },
  evidenceManagement: {
    list: '/api/v1/evidence-management',
    getById: (id: string) => `/api/v1/evidence-management/${id}`,
    create: '/api/v1/evidence-management',
    update: (id: string) => `/api/v1/evidence-management/${id}`,
    delete: (id: string) => `/api/v1/evidence-management/${id}`,
  },
  executiveDashboard: {
    list: '/api/v1/executive-dashboard',
    getById: (id: string) => `/api/v1/executive-dashboard/${id}`,
    create: '/api/v1/executive-dashboard',
    update: (id: string) => `/api/v1/executive-dashboard/${id}`,
    delete: (id: string) => `/api/v1/executive-dashboard/${id}`,
  },
  facilities: {
    list: '/api/v1/facilities',
    getById: (id: string) => `/api/v1/facilities/${id}`,
    create: '/api/v1/facilities',
    update: (id: string) => `/api/v1/facilities/${id}`,
    delete: (id: string) => `/api/v1/facilities/${id}`,
  },
  fireSafetySystems: {
    list: '/api/v1/fire-safety-systems',
    getById: (id: string) => `/api/v1/fire-safety-systems/${id}`,
    create: '/api/v1/fire-safety-systems',
    update: (id: string) => `/api/v1/fire-safety-systems/${id}`,
    delete: (id: string) => `/api/v1/fire-safety-systems/${id}`,
  },
  fleetManagement: {
    list: '/api/v1/fleet-management',
    getById: (id: string) => `/api/v1/fleet-management/${id}`,
    create: '/api/v1/fleet-management',
    update: (id: string) => `/api/v1/fleet-management/${id}`,
    delete: (id: string) => `/api/v1/fleet-management/${id}`,
  },
  forensic: {
    list: '/api/v1/forensic',
    getById: (id: string) => `/api/v1/forensic/${id}`,
    create: '/api/v1/forensic',
    update: (id: string) => `/api/v1/forensic/${id}`,
    delete: (id: string) => `/api/v1/forensic/${id}`,
  },
  gateway: {
    list: '/api/v1/gateway',
    getById: (id: string) => `/api/v1/gateway/${id}`,
    create: '/api/v1/gateway',
    update: (id: string) => `/api/v1/gateway/${id}`,
    delete: (id: string) => `/api/v1/gateway/${id}`,
  },
  giteaSourceControl: {
    list: '/api/v1/gitea-source-control',
    getById: (id: string) => `/api/v1/gitea-source-control/${id}`,
    create: '/api/v1/gitea-source-control',
    update: (id: string) => `/api/v1/gitea-source-control/${id}`,
    delete: (id: string) => `/api/v1/gitea-source-control/${id}`,
  },
  grafanaVisualization: {
    list: '/api/v1/grafana-visualization',
    getById: (id: string) => `/api/v1/grafana-visualization/${id}`,
    create: '/api/v1/grafana-visualization',
    update: (id: string) => `/api/v1/grafana-visualization/${id}`,
    delete: (id: string) => `/api/v1/grafana-visualization/${id}`,
  },
  housekeeping: {
    list: '/api/v1/housekeeping',
    getById: (id: string) => `/api/v1/housekeeping/${id}`,
    create: '/api/v1/housekeeping',
    update: (id: string) => `/api/v1/housekeeping/${id}`,
    delete: (id: string) => `/api/v1/housekeeping/${id}`,
  },
  hr: {
    list: '/api/v1/hr',
    getById: (id: string) => `/api/v1/hr/${id}`,
    create: '/api/v1/hr',
    update: (id: string) => `/api/v1/hr/${id}`,
    delete: (id: string) => `/api/v1/hr/${id}`,
  },
  iam: {
    list: '/api/v1/iam',
    getById: (id: string) => `/api/v1/iam/${id}`,
    create: '/api/v1/iam',
    update: (id: string) => `/api/v1/iam/${id}`,
    delete: (id: string) => `/api/v1/iam/${id}`,
  },
  icu: {
    list: '/api/v1/icu',
    getById: (id: string) => `/api/v1/icu/${id}`,
    create: '/api/v1/icu',
    update: (id: string) => `/api/v1/icu/${id}`,
    delete: (id: string) => `/api/v1/icu/${id}`,
  },
  incidentManagement: {
    list: '/api/v1/incident-management',
    getById: (id: string) => `/api/v1/incident-management/${id}`,
    create: '/api/v1/incident-management',
    update: (id: string) => `/api/v1/incident-management/${id}`,
    delete: (id: string) => `/api/v1/incident-management/${id}`,
  },
  infection: {
    list: '/api/v1/infection',
    getById: (id: string) => `/api/v1/infection/${id}`,
    create: '/api/v1/infection',
    update: (id: string) => `/api/v1/infection/${id}`,
    delete: (id: string) => `/api/v1/infection/${id}`,
  },
  infectionControl: {
    list: '/api/v1/infection-control',
    getById: (id: string) => `/api/v1/infection-control/${id}`,
    create: '/api/v1/infection-control',
    update: (id: string) => `/api/v1/infection-control/${id}`,
    delete: (id: string) => `/api/v1/infection-control/${id}`,
  },
  insuranceIntegration: {
    list: '/api/v1/insurance-integration',
    getById: (id: string) => `/api/v1/insurance-integration/${id}`,
    create: '/api/v1/insurance-integration',
    update: (id: string) => `/api/v1/insurance-integration/${id}`,
    delete: (id: string) => `/api/v1/insurance-integration/${id}`,
  },
  inventory: {
    list: '/api/v1/inventory',
    getById: (id: string) => `/api/v1/inventory/${id}`,
    create: '/api/v1/inventory',
    update: (id: string) => `/api/v1/inventory/${id}`,
    delete: (id: string) => `/api/v1/inventory/${id}`,
  },
  iotMessaging: {
    list: '/api/v1/iot-messaging',
    getById: (id: string) => `/api/v1/iot-messaging/${id}`,
    create: '/api/v1/iot-messaging',
    update: (id: string) => `/api/v1/iot-messaging/${id}`,
    delete: (id: string) => `/api/v1/iot-messaging/${id}`,
  },
  jaegerTracing: {
    list: '/api/v1/jaeger-tracing',
    getById: (id: string) => `/api/v1/jaeger-tracing/${id}`,
    create: '/api/v1/jaeger-tracing',
    update: (id: string) => `/api/v1/jaeger-tracing/${id}`,
    delete: (id: string) => `/api/v1/jaeger-tracing/${id}`,
  },
  jitsiConferencing: {
    list: '/api/v1/jitsi-conferencing',
    getById: (id: string) => `/api/v1/jitsi-conferencing/${id}`,
    create: '/api/v1/jitsi-conferencing',
    update: (id: string) => `/api/v1/jitsi-conferencing/${id}`,
    delete: (id: string) => `/api/v1/jitsi-conferencing/${id}`,
  },
  keycloak: {
    list: '/api/v1/keycloak',
    getById: (id: string) => `/api/v1/keycloak/${id}`,
    create: '/api/v1/keycloak',
    update: (id: string) => `/api/v1/keycloak/${id}`,
    delete: (id: string) => `/api/v1/keycloak/${id}`,
  },
  knowledgeGraphEngine: {
    list: '/api/v1/knowledge-graph-engine',
    getById: (id: string) => `/api/v1/knowledge-graph-engine/${id}`,
    create: '/api/v1/knowledge-graph-engine',
    update: (id: string) => `/api/v1/knowledge-graph-engine/${id}`,
    delete: (id: string) => `/api/v1/knowledge-graph-engine/${id}`,
  },
  kongGateway: {
    list: '/api/v1/kong-gateway',
    getById: (id: string) => `/api/v1/kong-gateway/${id}`,
    create: '/api/v1/kong-gateway',
    update: (id: string) => `/api/v1/kong-gateway/${id}`,
    delete: (id: string) => `/api/v1/kong-gateway/${id}`,
  },
  legal: {
    list: '/api/v1/legal',
    getById: (id: string) => `/api/v1/legal/${id}`,
    create: '/api/v1/legal',
    update: (id: string) => `/api/v1/legal/${id}`,
    delete: (id: string) => `/api/v1/legal/${id}`,
  },
  legalCaseManagement: {
    list: '/api/v1/legal-case-management',
    getById: (id: string) => `/api/v1/legal-case-management/${id}`,
    create: '/api/v1/legal-case-management',
    update: (id: string) => `/api/v1/legal-case-management/${id}`,
    delete: (id: string) => `/api/v1/legal-case-management/${id}`,
  },
  legalRiskAnalytics: {
    list: '/api/v1/legal-risk-analytics',
    getById: (id: string) => `/api/v1/legal-risk-analytics/${id}`,
    create: '/api/v1/legal-risk-analytics',
    update: (id: string) => `/api/v1/legal-risk-analytics/${id}`,
    delete: (id: string) => `/api/v1/legal-risk-analytics/${id}`,
  },
  litigationTracking: {
    list: '/api/v1/litigation-tracking',
    getById: (id: string) => `/api/v1/litigation-tracking/${id}`,
    create: '/api/v1/litigation-tracking',
    update: (id: string) => `/api/v1/litigation-tracking/${id}`,
    delete: (id: string) => `/api/v1/litigation-tracking/${id}`,
  },
  lokiLogging: {
    list: '/api/v1/loki-logging',
    getById: (id: string) => `/api/v1/loki-logging/${id}`,
    create: '/api/v1/loki-logging',
    update: (id: string) => `/api/v1/loki-logging/${id}`,
    delete: (id: string) => `/api/v1/loki-logging/${id}`,
  },
  management: {
    list: '/api/v1/management',
    getById: (id: string) => `/api/v1/management/${id}`,
    create: '/api/v1/management',
    update: (id: string) => `/api/v1/management/${id}`,
    delete: (id: string) => `/api/v1/management/${id}`,
  },
  marketing: {
    list: '/api/v1/marketing',
    getById: (id: string) => `/api/v1/marketing/${id}`,
    create: '/api/v1/marketing',
    update: (id: string) => `/api/v1/marketing/${id}`,
    delete: (id: string) => `/api/v1/marketing/${id}`,
  },
  medicalEducation: {
    list: '/api/v1/medical-education',
    getById: (id: string) => `/api/v1/medical-education/${id}`,
    create: '/api/v1/medical-education',
    update: (id: string) => `/api/v1/medical-education/${id}`,
    delete: (id: string) => `/api/v1/medical-education/${id}`,
  },
  medicalRecords: {
    list: '/api/v1/medical-records',
    getById: (id: string) => `/api/v1/medical-records/${id}`,
    create: '/api/v1/medical-records',
    update: (id: string) => `/api/v1/medical-records/${id}`,
    delete: (id: string) => `/api/v1/medical-records/${id}`,
  },
  mlflow: {
    list: '/api/v1/mlflow',
    getById: (id: string) => `/api/v1/mlflow/${id}`,
    create: '/api/v1/mlflow',
    update: (id: string) => `/api/v1/mlflow/${id}`,
    delete: (id: string) => `/api/v1/mlflow/${id}`,
  },
  mortuaryManagement: {
    list: '/api/v1/mortuary-management',
    getById: (id: string) => `/api/v1/mortuary-management/${id}`,
    create: '/api/v1/mortuary-management',
    update: (id: string) => `/api/v1/mortuary-management/${id}`,
    delete: (id: string) => `/api/v1/mortuary-management/${id}`,
  },
  mpi: {
    list: '/api/v1/mpi',
    getById: (id: string) => `/api/v1/mpi/${id}`,
    create: '/api/v1/mpi',
    update: (id: string) => `/api/v1/mpi/${id}`,
    delete: (id: string) => `/api/v1/mpi/${id}`,
  },
  multiTenantIsolationManager: {
    list: '/api/v1/multi-tenant-isolation-manager',
    getById: (id: string) => `/api/v1/multi-tenant-isolation-manager/${id}`,
    create: '/api/v1/multi-tenant-isolation-manager',
    update: (id: string) => `/api/v1/multi-tenant-isolation-manager/${id}`,
    delete: (id: string) => `/api/v1/multi-tenant-isolation-manager/${id}`,
  },
  networkManagement: {
    list: '/api/v1/network-management',
    getById: (id: string) => `/api/v1/network-management/${id}`,
    create: '/api/v1/network-management',
    update: (id: string) => `/api/v1/network-management/${id}`,
    delete: (id: string) => `/api/v1/network-management/${id}`,
  },
  networkObservability: {
    list: '/api/v1/network-observability',
    getById: (id: string) => `/api/v1/network-observability/${id}`,
    create: '/api/v1/network-observability',
    update: (id: string) => `/api/v1/network-observability/${id}`,
    delete: (id: string) => `/api/v1/network-observability/${id}`,
  },
  networkProvisioning: {
    list: '/api/v1/network-provisioning',
    getById: (id: string) => `/api/v1/network-provisioning/${id}`,
    create: '/api/v1/network-provisioning',
    update: (id: string) => `/api/v1/network-provisioning/${id}`,
    delete: (id: string) => `/api/v1/network-provisioning/${id}`,
  },
  notification: {
    list: '/api/v1/notification',
    getById: (id: string) => `/api/v1/notification/${id}`,
    create: '/api/v1/notification',
    update: (id: string) => `/api/v1/notification/${id}`,
    delete: (id: string) => `/api/v1/notification/${id}`,
  },
  nursing: {
    list: '/api/v1/nursing',
    getById: (id: string) => `/api/v1/nursing/${id}`,
    create: '/api/v1/nursing',
    update: (id: string) => `/api/v1/nursing/${id}`,
    delete: (id: string) => `/api/v1/nursing/${id}`,
  },
  opa: {
    list: '/api/v1/opa',
    getById: (id: string) => `/api/v1/opa/${id}`,
    create: '/api/v1/opa',
    update: (id: string) => `/api/v1/opa/${id}`,
    delete: (id: string) => `/api/v1/opa/${id}`,
  },
  opensearchSearch: {
    list: '/api/v1/opensearch-search',
    getById: (id: string) => `/api/v1/opensearch-search/${id}`,
    create: '/api/v1/opensearch-search',
    update: (id: string) => `/api/v1/opensearch-search/${id}`,
    delete: (id: string) => `/api/v1/opensearch-search/${id}`,
  },
  operationalCommandCenter: {
    list: '/api/v1/operational-command-center',
    getById: (id: string) => `/api/v1/operational-command-center/${id}`,
    create: '/api/v1/operational-command-center',
    update: (id: string) => `/api/v1/operational-command-center/${id}`,
    delete: (id: string) => `/api/v1/operational-command-center/${id}`,
  },
  order: {
    list: '/api/v1/order',
    getById: (id: string) => `/api/v1/order/${id}`,
    create: '/api/v1/order',
    update: (id: string) => `/api/v1/order/${id}`,
    delete: (id: string) => `/api/v1/order/${id}`,
  },
  orders: {
    list: '/api/v1/orders',
    getById: (id: string) => `/api/v1/orders/${id}`,
    create: '/api/v1/orders',
    update: (id: string) => `/api/v1/orders/${id}`,
    delete: (id: string) => `/api/v1/orders/${id}`,
  },
  ot: {
    list: '/api/v1/ot',
    getById: (id: string) => `/api/v1/ot/${id}`,
    create: '/api/v1/ot',
    update: (id: string) => `/api/v1/ot/${id}`,
    delete: (id: string) => `/api/v1/ot/${id}`,
  },
  pam: {
    list: '/api/v1/pam',
    getById: (id: string) => `/api/v1/pam/${id}`,
    create: '/api/v1/pam',
    update: (id: string) => `/api/v1/pam/${id}`,
    delete: (id: string) => `/api/v1/pam/${id}`,
  },
  patient: {
    list: '/api/v1/patient',
    getById: (id: string) => `/api/v1/patient/${id}`,
    create: '/api/v1/patient',
    update: (id: string) => `/api/v1/patient/${id}`,
    delete: (id: string) => `/api/v1/patient/${id}`,
  },
  patientExperience: {
    list: '/api/v1/patient-experience',
    getById: (id: string) => `/api/v1/patient-experience/${id}`,
    create: '/api/v1/patient-experience',
    update: (id: string) => `/api/v1/patient-experience/${id}`,
    delete: (id: string) => `/api/v1/patient-experience/${id}`,
  },
  performanceIntelligence: {
    list: '/api/v1/performance-intelligence',
    getById: (id: string) => `/api/v1/performance-intelligence/${id}`,
    create: '/api/v1/performance-intelligence',
    update: (id: string) => `/api/v1/performance-intelligence/${id}`,
    delete: (id: string) => `/api/v1/performance-intelligence/${id}`,
  },
  performanceManagement: {
    list: '/api/v1/performance-management',
    getById: (id: string) => `/api/v1/performance-management/${id}`,
    create: '/api/v1/performance-management',
    update: (id: string) => `/api/v1/performance-management/${id}`,
    delete: (id: string) => `/api/v1/performance-management/${id}`,
  },
  perimeterSecurity: {
    list: '/api/v1/perimeter-security',
    getById: (id: string) => `/api/v1/perimeter-security/${id}`,
    create: '/api/v1/perimeter-security',
    update: (id: string) => `/api/v1/perimeter-security/${id}`,
    delete: (id: string) => `/api/v1/perimeter-security/${id}`,
  },
  pharmacy: {
    list: '/api/v1/pharmacy',
    getById: (id: string) => `/api/v1/pharmacy/${id}`,
    create: '/api/v1/pharmacy',
    update: (id: string) => `/api/v1/pharmacy/${id}`,
    delete: (id: string) => `/api/v1/pharmacy/${id}`,
  },
  physicalAccessControl: {
    list: '/api/v1/physical-access-control',
    getById: (id: string) => `/api/v1/physical-access-control/${id}`,
    create: '/api/v1/physical-access-control',
    update: (id: string) => `/api/v1/physical-access-control/${id}`,
    delete: (id: string) => `/api/v1/physical-access-control/${id}`,
  },
  populationHealth: {
    list: '/api/v1/population-health',
    getById: (id: string) => `/api/v1/population-health/${id}`,
    create: '/api/v1/population-health',
    update: (id: string) => `/api/v1/population-health/${id}`,
    delete: (id: string) => `/api/v1/population-health/${id}`,
  },
  postalMail: {
    list: '/api/v1/postal-mail',
    getById: (id: string) => `/api/v1/postal-mail/${id}`,
    create: '/api/v1/postal-mail',
    update: (id: string) => `/api/v1/postal-mail/${id}`,
    delete: (id: string) => `/api/v1/postal-mail/${id}`,
  },
  prometheusMonitoring: {
    list: '/api/v1/prometheus-monitoring',
    getById: (id: string) => `/api/v1/prometheus-monitoring/${id}`,
    create: '/api/v1/prometheus-monitoring',
    update: (id: string) => `/api/v1/prometheus-monitoring/${id}`,
    delete: (id: string) => `/api/v1/prometheus-monitoring/${id}`,
  },
  qualityManagement: {
    list: '/api/v1/quality-management',
    getById: (id: string) => `/api/v1/quality-management/${id}`,
    create: '/api/v1/quality-management',
    update: (id: string) => `/api/v1/quality-management/${id}`,
    delete: (id: string) => `/api/v1/quality-management/${id}`,
  },
  rcm: {
    list: '/api/v1/rcm',
    getById: (id: string) => `/api/v1/rcm/${id}`,
    create: '/api/v1/rcm',
    update: (id: string) => `/api/v1/rcm/${id}`,
    delete: (id: string) => `/api/v1/rcm/${id}`,
  },
  redisCache: {
    list: '/api/v1/redis-cache',
    getById: (id: string) => `/api/v1/redis-cache/${id}`,
    create: '/api/v1/redis-cache',
    update: (id: string) => `/api/v1/redis-cache/${id}`,
    delete: (id: string) => `/api/v1/redis-cache/${id}`,
  },
  redpandaConsole: {
    list: '/api/v1/redpanda-console',
    getById: (id: string) => `/api/v1/redpanda-console/${id}`,
    create: '/api/v1/redpanda-console',
    update: (id: string) => `/api/v1/redpanda-console/${id}`,
    delete: (id: string) => `/api/v1/redpanda-console/${id}`,
  },
  redpandaStreaming: {
    list: '/api/v1/redpanda-streaming',
    getById: (id: string) => `/api/v1/redpanda-streaming/${id}`,
    create: '/api/v1/redpanda-streaming',
    update: (id: string) => `/api/v1/redpanda-streaming/${id}`,
    delete: (id: string) => `/api/v1/redpanda-streaming/${id}`,
  },
  regulatorIntegration: {
    list: '/api/v1/regulator-integration',
    getById: (id: string) => `/api/v1/regulator-integration/${id}`,
    create: '/api/v1/regulator-integration',
    update: (id: string) => `/api/v1/regulator-integration/${id}`,
    delete: (id: string) => `/api/v1/regulator-integration/${id}`,
  },
  resourceOptimizationEngine: {
    list: '/api/v1/resource-optimization-engine',
    getById: (id: string) => `/api/v1/resource-optimization-engine/${id}`,
    create: '/api/v1/resource-optimization-engine',
    update: (id: string) => `/api/v1/resource-optimization-engine/${id}`,
    delete: (id: string) => `/api/v1/resource-optimization-engine/${id}`,
  },
  riskManagement: {
    list: '/api/v1/risk-management',
    getById: (id: string) => `/api/v1/risk-management/${id}`,
    create: '/api/v1/risk-management',
    update: (id: string) => `/api/v1/risk-management/${id}`,
    delete: (id: string) => `/api/v1/risk-management/${id}`,
  },
  role: {
    list: '/api/v1/role',
    getById: (id: string) => `/api/v1/role/${id}`,
    create: '/api/v1/role',
    update: (id: string) => `/api/v1/role/${id}`,
    delete: (id: string) => `/api/v1/role/${id}`,
  },
  rostering: {
    list: '/api/v1/rostering',
    getById: (id: string) => `/api/v1/rostering/${id}`,
    create: '/api/v1/rostering',
    update: (id: string) => `/api/v1/rostering/${id}`,
    delete: (id: string) => `/api/v1/rostering/${id}`,
  },
  scm: {
    list: '/api/v1/scm',
    getById: (id: string) => `/api/v1/scm/${id}`,
    create: '/api/v1/scm',
    update: (id: string) => `/api/v1/scm/${id}`,
    delete: (id: string) => `/api/v1/scm/${id}`,
  },
  securityIncidentResponse: {
    list: '/api/v1/security-incident-response',
    getById: (id: string) => `/api/v1/security-incident-response/${id}`,
    create: '/api/v1/security-incident-response',
    update: (id: string) => `/api/v1/security-incident-response/${id}`,
    delete: (id: string) => `/api/v1/security-incident-response/${id}`,
  },
  simulationWhatifEngine: {
    list: '/api/v1/simulation-whatif-engine',
    getById: (id: string) => `/api/v1/simulation-whatif-engine/${id}`,
    create: '/api/v1/simulation-whatif-engine',
    update: (id: string) => `/api/v1/simulation-whatif-engine/${id}`,
    delete: (id: string) => `/api/v1/simulation-whatif-engine/${id}`,
  },
  slaHealthManager: {
    list: '/api/v1/sla-health-manager',
    getById: (id: string) => `/api/v1/sla-health-manager/${id}`,
    create: '/api/v1/sla-health-manager',
    update: (id: string) => `/api/v1/sla-health-manager/${id}`,
    delete: (id: string) => `/api/v1/sla-health-manager/${id}`,
  },
  sonarqubeQuality: {
    list: '/api/v1/sonarqube-quality',
    getById: (id: string) => `/api/v1/sonarqube-quality/${id}`,
    create: '/api/v1/sonarqube-quality',
    update: (id: string) => `/api/v1/sonarqube-quality/${id}`,
    delete: (id: string) => `/api/v1/sonarqube-quality/${id}`,
  },
  stepCa: {
    list: '/api/v1/step-ca',
    getById: (id: string) => `/api/v1/step-ca/${id}`,
    create: '/api/v1/step-ca',
    update: (id: string) => `/api/v1/step-ca/${id}`,
    delete: (id: string) => `/api/v1/step-ca/${id}`,
  },
  strategicPlanning: {
    list: '/api/v1/strategic-planning',
    getById: (id: string) => `/api/v1/strategic-planning/${id}`,
    create: '/api/v1/strategic-planning',
    update: (id: string) => `/api/v1/strategic-planning/${id}`,
    delete: (id: string) => `/api/v1/strategic-planning/${id}`,
  },
  telemedicine: {
    list: '/api/v1/telemedicine',
    getById: (id: string) => `/api/v1/telemedicine/${id}`,
    create: '/api/v1/telemedicine',
    update: (id: string) => `/api/v1/telemedicine/${id}`,
    delete: (id: string) => `/api/v1/telemedicine/${id}`,
  },
  tfServing: {
    list: '/api/v1/tf-serving',
    getById: (id: string) => `/api/v1/tf-serving/${id}`,
    create: '/api/v1/tf-serving',
    update: (id: string) => `/api/v1/tf-serving/${id}`,
    delete: (id: string) => `/api/v1/tf-serving/${id}`,
  },
  threatDetection: {
    list: '/api/v1/threat-detection',
    getById: (id: string) => `/api/v1/threat-detection/${id}`,
    create: '/api/v1/threat-detection',
    update: (id: string) => `/api/v1/threat-detection/${id}`,
    delete: (id: string) => `/api/v1/threat-detection/${id}`,
  },
  transplant: {
    list: '/api/v1/transplant',
    getById: (id: string) => `/api/v1/transplant/${id}`,
    create: '/api/v1/transplant',
    update: (id: string) => `/api/v1/transplant/${id}`,
    delete: (id: string) => `/api/v1/transplant/${id}`,
  },
  transplantCoordination: {
    list: '/api/v1/transplant-coordination',
    getById: (id: string) => `/api/v1/transplant-coordination/${id}`,
    create: '/api/v1/transplant-coordination',
    update: (id: string) => `/api/v1/transplant-coordination/${id}`,
    delete: (id: string) => `/api/v1/transplant-coordination/${id}`,
  },
  treatmentPlan: {
    list: '/api/v1/treatment-plan',
    getById: (id: string) => `/api/v1/treatment-plan/${id}`,
    create: '/api/v1/treatment-plan',
    update: (id: string) => `/api/v1/treatment-plan/${id}`,
    delete: (id: string) => `/api/v1/treatment-plan/${id}`,
  },
  user: {
    list: '/api/v1/user',
    getById: (id: string) => `/api/v1/user/${id}`,
    create: '/api/v1/user',
    update: (id: string) => `/api/v1/user/${id}`,
    delete: (id: string) => `/api/v1/user/${id}`,
  },
  vault: {
    list: '/api/v1/vault',
    getById: (id: string) => `/api/v1/vault/${id}`,
    create: '/api/v1/vault',
    update: (id: string) => `/api/v1/vault/${id}`,
    delete: (id: string) => `/api/v1/vault/${id}`,
  },
  vendorManagement: {
    list: '/api/v1/vendor-management',
    getById: (id: string) => `/api/v1/vendor-management/${id}`,
    create: '/api/v1/vendor-management',
    update: (id: string) => `/api/v1/vendor-management/${id}`,
    delete: (id: string) => `/api/v1/vendor-management/${id}`,
  },
  visitorManagement: {
    list: '/api/v1/visitor-management',
    getById: (id: string) => `/api/v1/visitor-management/${id}`,
    create: '/api/v1/visitor-management',
    update: (id: string) => `/api/v1/visitor-management/${id}`,
    delete: (id: string) => `/api/v1/visitor-management/${id}`,
  },
  wazuh: {
    list: '/api/v1/wazuh',
    getById: (id: string) => `/api/v1/wazuh/${id}`,
    create: '/api/v1/wazuh',
    update: (id: string) => `/api/v1/wazuh/${id}`,
    delete: (id: string) => `/api/v1/wazuh/${id}`,
  },
  zeroTrustNetworkControl: {
    list: '/api/v1/zero-trust-network-control',
    getById: (id: string) => `/api/v1/zero-trust-network-control/${id}`,
    create: '/api/v1/zero-trust-network-control',
    update: (id: string) => `/api/v1/zero-trust-network-control/${id}`,
    delete: (id: string) => `/api/v1/zero-trust-network-control/${id}`,
  },
  zta: {
    list: '/api/v1/zta',
    getById: (id: string) => `/api/v1/zta/${id}`,
    create: '/api/v1/zta',
    update: (id: string) => `/api/v1/zta/${id}`,
    delete: (id: string) => `/api/v1/zta/${id}`,
  },
  ztaEngine: {
    list: '/api/v1/zta-engine',
    getById: (id: string) => `/api/v1/zta-engine/${id}`,
    create: '/api/v1/zta-engine',
    update: (id: string) => `/api/v1/zta-engine/${id}`,
    delete: (id: string) => `/api/v1/zta-engine/${id}`,
  },
  ueba: {
    list: '/api/v1/ueba/risk-scores',
    getById: (id: string) => `/api/v1/ueba/risk-scores/${id}`,
    create: '/api/v1/ueba/risk-scores',
    update: (id: string) => `/api/v1/ueba/risk-scores/${id}`,
    delete: (id: string) => `/api/v1/ueba/risk-scores/${id}`,
    anomalies: '/api/v1/ueba/anomalies',
    baselines: '/api/v1/ueba/baselines',
    events: '/api/v1/ueba/events',
  },
} as const;
